name: structopt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - openmm>=8.1
  - pdbfixer>=1.10
  - openmmforcefields>=0.12
  - ambertools
  - rdkit
  - pip:
      - typer>=0.12.5
      - pydantic>=2.9.0
      - numpy>=1.26.0
      - pytest>=8.3.0
      - pytest-cov>=5.0.0
      - ruff>=0.6.0
